services:
  frontend:
    build:
      context: ./frontend
    container_name: tripbuddy-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:4000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - gateway

  gateway:
    build:
      context: ./services/gateway
    container_name: tripbuddy-gateway
    ports:
      - "4000:4000"
    environment:
      GATEWAY_PORT: 4000
      IDENTITY_SERVICE_URL: http://identity-service:4001
      TRIP_SERVICE_URL: http://trip-service:4002
    volumes:
      - ./services/gateway:/app
      - /app/node_modules
    depends_on:
      - identity-service
      - trip-service

  identity-service:
    build:
      context: ./services/identity-service
    container_name: tripbuddy-identity-service
    ports:
      - "4001:4001"
    environment:
      IDENTITY_SERVICE_PORT: 4001
      IDENTITY_DB_HOST: identity-db
      IDENTITY_DB_PORT: 5432
      IDENTITY_DB_NAME: identity_db
      IDENTITY_DB_USER: postgres
      IDENTITY_DB_PASSWORD: postgres
      IDENTITY_JWT_SECRET: tripbuddy_identity_secret
    volumes:
      - ./services/identity-service:/app
      - /app/node_modules
    depends_on:
      - identity-db

  trip-service:
    build:
      context: ./services/trip-service
    container_name: tripbuddy-trip-service
    ports:
      - "4002:4002"
    environment:
      TRIP_SERVICE_PORT: 4002
      TRIP_DB_HOST: trip-db
      TRIP_DB_PORT: 5432
      TRIP_DB_NAME: trip_db
      TRIP_DB_USER: postgres
      TRIP_DB_PASSWORD: postgres
      TRIP_JWT_SECRET: tripbuddy_identity_secret
    volumes:
      - ./services/trip-service:/app
      - /app/node_modules
    depends_on:
      - trip-db

  identity-db:
    image: postgres:16
    container_name: tripbuddy-identity-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: identity_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - identity_db_data:/var/lib/postgresql/data

  trip-db:
    image: postgres:16
    container_name: tripbuddy-trip-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: trip_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - trip_db_data:/var/lib/postgresql/data

volumes:
  identity_db_data:
  trip_db_data:
